version: '3.9'

services:
  webhost:
    image: image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - D:\dbdata:/app/database
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    image: image
    build:
      context: .
      dockerfile: Dockerfile.migration
    volumes:
      - D:\dbdata:/app/database